##############
### prd
##############
server:
  port: 9080
  servlet:
    context-path: /
  tomcat:
    connection-timeout: 5s
    max-connections: 1000
    accept-count: 20
    threads:
      max: 200
spring:
  datasource:
    platform: mariadb
    #driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.43.13.1:32462/edu
    username: admin
    #password: caravan
    #password: ENC(hk5/B+52K9XaD+BqzpFaHQ==)
    password: New1234!
#    hikari:
#      pool-name: hikari-cp
#      maximum-pool-size: 30
#      minimum-idle: 2
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true

# app
app-info:
  node-ip: "192.168.0.1"
  pod-ip: "192.168.0.1"
  pod-name: "test"
  app-name: "edu11"

springdoc:
  show-actuator: true  # actuator swagger 노출
  swagger-ui:
    groups-order: DESC
    #operations-sorter: alpha
    #tags-sorter: alpha
    disable-swagger-default-url: true
    #doc-expansion: none

logging:
  level:
    com.kt.edu: trace
    org.springframework.security: DEBUG
    org:
      keycloak:
        admin:
          client: DEBUG